### ISSUE TITLE
Calibration error

### ISSUE THREAD

**Issue by oxicottin** [addicx/plantsensor#1]
I cant get calibration to work without the error below. line 7 in the cal example is csms.calibrate()

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "CSMS.py", line 65, in calibrate
  File "CSMS.py", line 89, in read_raw
AttributeError: 'ADC' object has no attribute 'read'

**Comment by SergeyMNet** [comment]
use self.adc.read_u16()
